# Generated by Django 5.1.6 on 2025-02-24 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VhicleModel',
            new_name='VehicleModel',
        ),
    ]
