# Generated by Django 5.1.6 on 2025-02-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_vhiclemodel_vehiclemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemodel',
            name='year',
            field=models.IntegerField(),
        ),
    ]
