# Generated by Django 5.1.6 on 2025-02-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_car_or_bike_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='car_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
