# Generated by Django 5.1 on 2025-02-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_car_name_vehicle_vehicle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='Bimage',
            field=models.ImageField(blank=True, null=True, upload_to='Vehice_images'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='Limage',
            field=models.ImageField(blank=True, null=True, upload_to='Vehice_images'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='Rimage',
            field=models.ImageField(blank=True, null=True, upload_to='Vehice_images'),
        ),
    ]
